---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding1
  namespace: default
subjects:
- kind: User
  name: virus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role1
  apiGroup: rbac.authorization.k8s.io
